#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - htop
  - vim
  - unzip

runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  
  # Add ubuntu user to docker group
  - usermod -aG docker ubuntu
  
  # Install Docker Compose standalone (for compatibility)
  - curl -L "https://github.com/docker/compose/releases/download/v${docker_compose_version}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  
  # Create app directory
  - mkdir -p /opt/haqnow-community
  - chown ubuntu:ubuntu /opt/haqnow-community
  
  # Enable and start Docker
  - systemctl enable docker
  - systemctl start docker

write_files:
  - path: /etc/systemd/system/haqnow-community.service
    content: |
      [Unit]
      Description=Haqnow Community Application
      Requires=docker.service
      After=docker.service
      
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/haqnow-community
      ExecStart=/usr/local/bin/docker-compose up -d
      ExecStop=/usr/local/bin/docker-compose down
      User=ubuntu
      Group=ubuntu
      
      [Install]
      WantedBy=multi-user.target
    permissions: '0644'

final_message: "Haqnow Community VM setup complete. Docker and Docker Compose installed."
