version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /srv
    command: bash -lc "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev && pip install poetry && cd backend && poetry install && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ..:/srv:cached
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: python:3.11-slim
    working_dir: /srv
    command: bash -lc "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng libtesseract-dev && pip install poetry && cd backend && poetry install && poetry run celery -A app.celery_app worker --loglevel=info"
    volumes:
      - ..:/srv:cached
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"


